name: csol
version: 1.0.0
main: csol
description: Counter-Strike of Legends
author: suzakuwcx.com
website: https://www.spigotmc.org/
api-version: '1.20'

commands:
  csol:
    description: Your description
    usage: /csol <subcommand>
    permission: csol.csol

  cu:
    description: Your description
    usage: /cu <subcommand>
    permission: csol.cu

  ca:
    description: Your description
    usage: /ca <subcommand>
    permission: csol.ca
